### PR TITLE
get travis ci working

### PR DESCRIPTION
**Pull request by jamesmanning**

### CODE REVIEW

**Comment by jamesmanning** [comment]
@EamonNerbonne FWIW now that we have CI working, this should hopefully help prevent any future recurrence of the truncation issue. :smile:

**Comment by EamonNerbonne** [comment]
That's one long-running test there :-).  You managed to capture the race condition somewhat reliably in a test?  (incidentally, this race-condition occurred for me even for much shorter runs of a few seconds, though I'm not sure it did so reliably)

**Comment by jamesmanning** [comment]
"Reliably" might be relative here, but of the ten or so times I ran the
long-running test, it always failed (hitting the output truncation) within
the first 10 seconds.

Since you have me curious now, I'll checkout that commit (the commit work
the failing test went in before the fix) and have it run to failure N times
and see how long it takes to fail.

Admittedly, this is very likely to be highly machine specific, and I'm not
sure how long it would take it to fail on the Travis CI docker containers.
However, I'll make a branch and pull request to see what Travis reports. :)

**Comment by jamesmanning** [comment]
@EamonNerbonne I couldn't get it to reliably happen in a reasonable amount of time when running 1 at a time, but it always happened in 60 seconds or less once I had it run many in parallel

```csharp
Parallel.ForEach(Enumerable.Range(1, 100), index => WhenProcessReturnsLotsOfOutput_AllOutputCapturedCorrectly());
```

Funny enough, once I did that, along with the original "sometimes the output is truncated", I now got crashes as the stdout.ToArray() call would fail during process exit, as it would hit a race condition where a new item got inserted after it had already allocated the target array to copy to.

https://ci.appveyor.com/project/jamesmanning/runprocessastask/build/1.0.18

    System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
       at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
       at System.Collections.Generic.List`1.ToArray()
       at RunProcessAsTask.ProcessEx.<>c__DisplayClass1_0.<RunAsync>b__2(Object sender, EventArgs args) in C:\projects\runprocessastask\src\RunProcessAsTask\ProcessEx.cs:line 50
       at System.Diagnostics.Process.OnExited()
       at System.Diagnostics.Process.RaiseOnExited()
       at System.Diagnostics.Process.CompletionCallback(Object context, Boolean wasSignaled)

Since this was testing the known-broken original code (before any fix applied), I didn't bother going down the path of trying to catch the exception in the Exited event to continue to get more timing numbers, but thought you might find that amusing since you had correctly stated that the ToArray wasn't thread-safe (since the output hadn't closed and was still writing to the list).

In any case, I feel *fairly* (not highly) confident that with the parallelism enabled now, if it survives for 5 minutes, then that bug hasn't regressed. :smile:

**Comment by EamonNerbonne** [comment]
This kind of stuff you'll never manage to test exhaustively anyhow - at least, not without some fairly invasive, hard to set up threading simulators.  Neat that you managed to get that far in the first place!

**Pull request merged**
