### PR TITLE
Fix process exit race condition

### PR DESCRIPTION
**Pull request by jamesmanning**

### CODE REVIEW

**Comment by EamonNerbonne** [comment]
33db321 looks great to me!

**Comment by jamesmanning** [comment]
@EamonNerbonne awesome, thank you for reviewing it!

**Comment by EamonNerbonne** [comment]
Thank you for making it ;-).  Now I can dump my ProcessRunners and just use this!

**Comment by jamesmanning** [comment]
It's up on NuGet.org now FWIW https://www.nuget.org/packages/RunProcessAsTask/1.1.3

**Pull request merged**
