### PR TITLE
dot net core support

### PR DESCRIPTION
**Pull request by EamonNerbonne**
This adds a few commits to #12.

Added value is primarily cleanup, but I also integrated the nuspec into the project file.

I autoformatted a bunch of files to restore the 4-based indent.  Unfortunately, that also caused a few more spurious changes.  You'll have to judge if that's a problem, of course.

While autoformatting, I encountered ProcessResults, and I noticed it was manually creating get-only properties; there's syntax for than nowadays, so I used that.  I also made the class sealed, since it's `IDisposable` and the alternative is much messier and confusing (microsoft's virtual Dispose(bool) pattern).

This does not yet include multitargetting.  That may be a trivial change, but it might not be, so I didn't want to confuse matters.

### CODE REVIEW

**Comment by EamonNerbonne** [comment]
The tests do not work on my machine; the RunProcessAsTask appears to work, but the dummy app can't be loaded, the `dotnet` command fails with the message that...

`A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\VCS\external\RunProcessAsTask\src\RunProcessAsTask.Tests\bin\Debug\netcoreapp1.1'.`

A little googling suggests this isn't a new error, but also that it should not be occurring anymore (I've got CLI 1.0.3, .net core 1.1.0).  It may just be my configuration; but the version from #12 doesn't work either.

running something like `xcopy` works fine.

**Comment by jamesmanning** [comment]
@EamonNerbonne given you and @MaxCheetham both clearly know more about the core side of things, I think it makes more sense to let you guys just work in the repo directly instead of having to work through pull requests - I'll help out as I can, but at this point I'm more of a bottleneck and I'd rather unblock your collective efforts. 😄   I've added you both as collaborators.  If you can tell me how with the new tooling, I'm happy to build a nuget pkg to test with as a consumer (and/or push as a prerelease version up to nuget.org)

**Comment by EamonNerbonne** [comment]
So the issue with testing before this PR was simply that I had a dirty build.  And that's actually informative, because this is failing because the `PackageReference` isn't taking along the `.runtimeconfig.json` files the .net core cli tool needs to run; this looks like a tooling bug to me.  Related: https://github.com/dotnet/sdk/pull/768 - but that bug is about `.runtimeconfig.json` files missing from nuget output, but apparently it's also missing in this scenario.

Since this is totally irrelevant to this project, a simple workaround here might be to use a shared output folder and be done with file-copy problems.

**Comment by EamonNerbonne** [comment]
@jamesmanning if you want to pack and push any new-style projects (also works for net framwork targetting projects, incidentally):

```
    dotnet pack -c release --include-symbols --include-source
    dotnet nuget push -s https://www.nuget.org/api/v2/package .\bin\Release\<package-name>.<version>.nupkg
```

(Assumes you've already done `nuget setApiKey <your-api-key-here>`)

Such a push includes source to source servers, which works fine on push, but I've never managed to get VS to read those properly, so that part is still a theoretical advantage so far.

**Comment by EamonNerbonne** [comment]
So coverage isn't checked now; but appveyor is green again.  Travis is reporting an error, but it looks like that might be a real error: is `Process.StartTime` actually supported on dotnet on ubuntu after process exit?  No idea.

**Comment by EamonNerbonne** [comment]
As far as I'm concerned, this looks mergable now.  @jamesmanning or @MaxCheetham ?

**Comment by MaxCheetham** [comment]
@EamonNerbonne @jamesmanning Are we wanting the Travis build to be fixed for the integration before we merge? I'm out in the sun for most of today but i'm more than happy to pull your more recent changes down to my machine and run the local tests later on today?

**Comment by MaxCheetham** [comment]
@jamesmanning Also. Before we pack merge and pack this PR would you be ok with me and @EamonNerbonne naming ourselves as authors on the NuGet package?

**Comment by jamesmanning** [comment]
Of course! Please do!

**Comment by MaxCheetham** [comment]
I'm also happy with the ProcessResults refactoring

**Comment by MaxCheetham** [comment]
Closing this now we can both Collab. I have opened a new PR baised off this repo.

**Pull request closed without merging**
